### PR TITLE
Bugfix/french strings

### PR DESCRIPTION
**Pull request by FBergeron**
I have corrected some strings in French.

### CODE REVIEW

**Comment by basildane** [comment]
I noticed there is only one string that is missing from the French translation.  "Show splash screen".  If you would like to send me that I'll put it in there too.

**Comment by FBergeron** [comment]
I did:

grep -r "splash" .

but didn't find anything relevant so I don't know where to perform the modification.  Nonetheless, here is how I would translate that:

"Afficher l'écran de démarrage"

**Comment by basildane** [comment]
I don't think the string exists in the french.resx file.  Thanks, I'll put this in.

**Comment by basildane** [comment]
It actually belongs in the OptionProperties.fr.resx file.  I added it.

image

**Comment by FBergeron** [comment]
It looks good but I notice that the string EnableSound has not been translated.  I will review all the strings and report.

**Comment by FBergeron** [comment]
The other strings look good I think.  I don't know why but your screenshot seems out of sync with the code.

**Comment by basildane** [comment]
> The other strings look good I think. I don't know why but your screenshot seems out of sync with the code.

Please give one example of what's out of sync, I will investigate.

**Comment by FBergeron** [comment]
I meant that on the screenshot in your previous message, there are these 3 strings in English:
"Emergency settings", "Shutdown", and "EnableSound" .  So I thought that some other strings were not translated.  After verification, I can see that these strings (actually all the strings) are properly translated in the source code.  I don't know why they appear in English in your screenshot but I guess that everything is ok after all.

**Comment by basildane** [comment]
It should be displaying the translated strings.  I will fix it.

**Comment by FBergeron** [comment]
One last thing. I want to thank you for your work. Your application is very useful.

**Comment by basildane** [comment]
Thank you, I'm glad you enjoyed it.

**Pull request closed without merging**
