### PR TITLE
Merge non captitalized 'installer' folder with the capitalized 'Insta…

### PR DESCRIPTION
**Pull request by ronaldhoek**
Merge non capitalized 'installer' folder with the already available capitalized 'Installer' folder

### CODE REVIEW

**Comment by basildane** [comment]
Thank you!  I wish I had more time to spend on this project like I did in the old days.

**Comment by ronaldhoek** [comment]
Well, you did a great job and it's still working!

But nowadays I only use the WOL-library for my WakeOnLanPortal project (https://github.com/ronaldhoek/WakeOnLanPortal), for which I recently created a LITE version (https://github.com/ronaldhoek/WakeOnLanPortalLite) so it would also work on mobile devices (but without authentication thru the application - you need to configure IIS with Windows or Basic Auth to require login featues).

**Comment by ronaldhoek** [comment]
I'll update it immediately so it references https://github.com/basildane/WakeOnLAN and https://wol.aquilatech.com/

**Comment by basildane** [comment]
Do you have any screenshots of your application?

**Comment by ronaldhoek** [comment]
image

**Pull request merged**
